# Generated by Django 4.1.7 on 2023-04-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.TextField(max_length=50)),
                ('tipo', models.TextField(max_length=50)),
                ('categoria', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.TextField(max_length=100)),
                ('materia', models.TextField(max_length=100)),
                ('fecha_parcial', models.DateTimeField(auto_now_add=True)),
                ('nota_parcial', models.TextField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(max_length=100)),
                ('nombre', models.TextField(max_length=100)),
                ('apellido', models.TextField(max_length=100)),
                ('fecha_nacimiento', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
