# Generated by Django 4.1.7 on 2023-04-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega_final_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('tipo', models.TextField(max_length=50)),
                ('rating', models.TextField(max_length=10)),
                ('categoria', models.TextField(max_length=50)),
                ('opinion', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Elementos',
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
