# Generated by Django 4.1.7 on 2023-04-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega_final_app', '0002_juegos_delete_elementos_delete_notas_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='opinion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='rating',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
