# Generated by Django 4.1.7 on 2023-04-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega_final_app', '0004_juegos_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
