# Generated by Django 4.1.7 on 2023-04-22 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entrega_final_app', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='creado_el',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
