# Generated by Django 4.1.7 on 2023-04-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega_final_app', '0008_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
